"""initial

Revision ID: 4d39cfbf6552
Revises: 
Create Date: 2024-12-12 12:32:23.652310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d39cfbf6552"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acst_files_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("acst_number", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("ident"),
    )
    op.create_table(
        "personal_naks_certification_files_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("certification_number", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("ident"),
    )
    op.create_table(
        "personal_naks_protocol_files_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("protocol_number", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("ident"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personal_naks_protocol_files_table")
    op.drop_table("personal_naks_certification_files_table")
    op.drop_table("acst_files_table")
    # ### end Alembic commands ###
